version: '2'
services:
    web:
        build: .
        command: bin/rails server --port 3000 --binding 0.0.0.0
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/src/app
            - bundle:/bundle
        depends_on:
            - redis
            - solr
            - fcrepo
            - mysql

    redis:
        image: redis:3
        ports:
          - "6379:6379"
    mysql:
        image: mysql:5.6
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
    solr:
        image: solr:5.5
        ports:
          - "8983:8983"
        volumes:
          - ./solr/config:/opt/config
    fcrepo:
        image: botimer/misc:fcrepo-45
        ports:
          - "8984:8080"

volumes:
    bundle:
        driver: local

