version: '2'
services:
    web:
        build: .
        command: bin/rails server --port 3000 --binding 0.0.0.0
        ports:
            - "3000:3000"
        links:
            - redis
            # - mysql
            - solr
            - fcrepo
        volumes:
            - .:/usr/src/app
        volumes_from:
            - bundle

    bundle:
        image: shello_web
        command: echo Data container... Online
        volumes:
            - /bundle

    redis:
        image: redis:3
        ports:
          - "6379:6379"
    # mysql:
    #     image: mysql:5.6
    #     environment:
    #       - MYSQL_ALLOW_EMPTY_PASSWORD=true
    solr:
        image: solr:5.5
        ports:
          - "8983:8983"
    fcrepo:
        image: fcrepo:4.5
        ports:
          - "8984:8080"


