# We are moving sufia into the 20000 range.
version: '2'
services:
    web:
        build: .
        command: bin/rails server --port 3000 --binding 0.0.0.0
        ports:
            - "23000:3000"
        volumes:
            - .:/usr/src/app
            - bundle:/bundle
#        volumes_from:
#            - unison
        depends_on:
            - redis
            - solr
            - fcrepo
            - mysql
    redis:
        image: redis:3
        ports:
          - "6379:6379"
    mysql:
#        ports:
#          - "3306:3306"
        image: mysql:5.6
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
    solr:
        image: solr:5.5
        ports:
          - "8983:8983"
        volumes:
          - ./solr/config:/opt/config
    fcrepo:
        image: botimer/fcrepo:4.5.1
        volumes:
            - fcrepo_data:/opt/data
        ports:
          - "8080:8080"

volumes:
    bundle:
        driver: local
    fcrepo_data:
        driver: local
