version: '2'
services:
    web:
        build: .
        command: bin/rails server --port 3000 --binding 0.0.0.0
        ports:
            - "3000:3000"
        volumes:
            # Mount the volume from the unison container instead of host path
            # - .:/usr/src/app
            - bundle:/bundle
        volumes_from:
            - unison
        depends_on:
            - redis
            - solr
            - fcrepo
            - mysql

    redis:
        image: redis:3
        ports:
          - "6379:6379"
    mysql:
        image: mysql:5.6
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
    solr:
        image: solr:5.5
        ports:
          - "8983:8983"
        volumes:
          - ./solr/config:/opt/config
    fcrepo:
        image: lyrasis/fcrepo:4.5.0
        volumes:
            - fcrepo_data:/opt/data
        ports:
          - "8984:8080"
    unison:
        # image: leighmcculloch/unison
        image: botimer/unison-fsmonitor
        environment:
            - UNISON_PATH=/usr/src/app
        volumes:
            - /usr/src/app
        ports:
            - "5000:5000"

volumes:
    bundle:
        driver: local
    fcrepo_data:
        driver: local

